---
- name: Ensure deploy directory exists
  ansible.builtin.file:
    path: "{{ deploy_path }}"
    state: directory
    owner: "{{ deploy_owner }}"
    group: "{{ deploy_group }}"
    mode: "{{ deploy_directory_mode }}"
